Campaign list on index page
CraftAcademy/care2share pull request #4
Opened 2018-12-04 15:28 UTC by schneiderman805

## PT: 
[Link to PT](https://www.pivotaltracker.com/story/show/162396962)

## User story:
```
As a User
In order to know which campaigns I can donate to
I would like to see a list of available campaigns on the index page
```
## Actions taken:

- Adds controller model and views for index page

- Adds validation 

## Lessons learned:

- Watch out for typos
<img width="619" alt="screenshot 2018-12-04 at 19 28 05" src="https://user-images.githubusercontent.com/43759826/49464327-e7582b80-f7fa-11e8-8ce2-25163f3c3942.png">

2018-12-04 15:49 UTC, CamronLDNF reviewed
As discussed, let's move the image attribute from the campaign cards out to its own user story and for later date to implement.

2018-12-04 15:49 UTC, HannaSwDn approved these changes

2018-12-04 16:01 UTC, faraznaeem requested changes

2018-12-04 16:01 UTC, faraznaeem commented on app/models/campaign.rb
> +    validates :amount_raised, presence: true
`validates_presence_of :title, :description, :amount_raised`

2018-12-04 16:01 UTC, faraznaeem commented on config/routes.rb
> +  get 'campaigns/index'
remove the route
please use `--skip-routes` when you are using the controller generate command

2018-12-04 16:01 UTC, faraznaeem commented on features/User_can_see_the_campaigns_on_Index_page.feature
> +        When I visit the site
`And i visit the site`

2018-12-04 16:01 UTC, faraznaeem commented on spec/modles/campaigns_spec.rb
> +require 'rails_helper'
`spec/modles/campaigns_spec.rb` ???
 why didn't you use the scaffolded file?

2018-12-04 16:01 UTC, faraznaeem commented on app/assets/stylesheets/campaigns.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
Why are these files created, aren't the generators not turned off?

2018-12-04 16:07 UTC, faraznaeem requested changes

2018-12-04 16:07 UTC, faraznaeem commented on app/views/campaigns/index.html.haml
> +    %p= campaign.amount_raised
please add a screenshot

2018-12-04 18:17 UTC, schneiderman805 commented on app/models/campaign.rb
> +    validates :amount_raised, presence: true
we have refactored code into one line

2018-12-04 18:19 UTC, schneiderman805 commented on config/routes.rb
> +  get 'campaigns/index'
we have removed the route

2018-12-04 18:20 UTC, schneiderman805 commented on features/User_can_see_the_campaigns_on_Index_page.feature
> +        When I visit the site
we have changed When to And

2018-12-04 18:23 UTC, schneiderman805 commented on spec/modles/campaigns_spec.rb
> +require 'rails_helper'
we had duplicate files so we removed one

2018-12-04 18:25 UTC, schneiderman805 commented on app/assets/stylesheets/campaigns.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
we are not quite sure, we could possible use a little explaining please.

2018-12-04 18:29 UTC, schneiderman805 commented on app/views/campaigns/index.html.haml
> +    %p= campaign.amount_raised
we have taken a screen shot and added it to this PR.

2018-12-04 18:38 UTC, HannaSwDn approved these changes

2018-12-05 09:28 UTC, faraznaeem approved these changes

2018-12-05 09:28 UTC, merged