Sets up coveralls
CraftAcademy/care2share pull request #5
Opened 2018-12-04 15:54 UTC by HannaSwDn

## PT:
[Link to PT](https://www.pivotaltracker.com/story/show/162407729)

## Actions taken:
Adds coveralls for test coverage report

## Lessons learned:
The meaning of coveralls and how to set it up

2018-12-04 16:01 UTC, schneiderman805 reviewed
I have reviewed it and it looks good, had to do it on my phone. If you would like to go over it with me later tonight that’s cool.

2018-12-04 18:15 UTC, shahin1290 approved these changes
It look fine to me

2018-12-04 19:16 UTC, oliverochman requested changes

2018-12-04 19:16 UTC, oliverochman commented on coverage/.resultset.json
> +{
you need to add `coverage/*` to the .gitignore

2018-12-05 15:26 UTC, HannaSwDn commented on coverage/.resultset.json
> +{
Done

2018-12-05 15:27 UTC, merged